### ISSUE TITLE
Allow logging of DELETE requests

### ISSUE THREAD

**Issue by NodeJSmith** [vishalanandl177/DRF-API-Logger#22]
Have you considered adding logging of DELETE requests? These are not logged now since they do not have a content-type, but deleting resources seems to be something you would want to log. I've patched my copy and it's only a few lines of code changes to allow it to log DELETE requests also.

**Comment by vishalanandl177** [comment]
Delete requests have method DELETE and you can specify content type application/json because delete requests should also have a content type.

Please explain the scenario that you are facing.

**Comment by vishalanandl177** [comment]
All the APIs are currently being logged with content type application/json irrespective of their request method.

**Comment by vishalanandl177** [comment]
Closing due to inactivity.

**Comment by MertcanGokgoz** [comment]
@vishalanandl177 It may be giving an error that there is no content-type value in DELETE requests.

I made a small project to test it and the result was exactly as I thought. Normally, content-type should be sent in DELETE request, but people forget. 😞 

```
ERROR 2021-07-02 21:45:21,348 log 14106 140705418586576 Internal Server Error: /test/data/1/delete
Traceback (most recent call last):
  File "/home/test/miniconda3/envs/test/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/test/miniconda3/envs/test/lib/python3.9/site-packages/drf_api_logger/middleware/api_logger_middleware.py", line 84, in __call__
    if 'content-type' in response and response['content-type'] == 'application/json' or response['content-type'] == 'application/vnd.api+json':
  File "/home/test/miniconda3/envs/test/lib/python3.9/site-packages/django/http/response.py", line 144, in __getitem__
    return self._headers[header.lower()][1]
KeyError: 'content-type'
```

a few minor changes can be made to control such situations.

**Comment by vishalanandl177** [comment]
Sure. I'll look into this ASAP.
Thanks for the support.

**Comment by vishalanandl177** [comment]
Try updating the library to latest version in the same project.
This may not give any errors.

**Comment by MertcanGokgoz** [comment]
> Try updating the library to latest version in the same project.
> This may not give any errors.

I updated the plugin and tried again. No problem appears.

Thanks 👍🏻
