### ISSUE TITLE
KeyError at /manage-console/drf_api_logger/apilogsmodel/  'cl'

### ISSUE THREAD

**Issue by jatindergit** [vishalanandl177/DRF-API-Logger#35]
Internal Server Error: /manage-console/drf_api_logger/apilogsmodel/
Traceback (most recent call last):
  File "/Python/env/lib/python3.8/site-packages/asgiref/sync.py", line 458, in thread_handler
    raise exc_info[1]
  File "/Python/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/Python/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Python/env/lib/python3.8/site-packages/asgiref/sync.py", line 423, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/Python/env/lib/python3.8/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Python/env/lib/python3.8/site-packages/asgiref/sync.py", line 462, in thread_handler
    return func(*args, **kwargs)
  File "/Python/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Python/env/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Python/env/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Python/env/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 232, in inner
    return view(request, *args, **kwargs)
  File "/Python/env/lib/python3.8/site-packages/drf_api_logger/admin.py", line 90, in changelist_view
    filtered_query_set = response.context_data["cl"].queryset
KeyError: 'cl'

This is happening when i try to delete all the logs from django admin

**Comment by vishalanandl177** [comment]
Hi @jatindergit I'll look into this issue ASAP.

**Comment by vishalanandl177** [comment]
This issue has been resolved.
I'm releasing a newer version (1.0.10).
